
extern const char *g_sChooseServer;
extern const char *g_sInputAccount ;
extern const char *g_sInputPassword ;
extern const char *g_sInputMail;
extern const char *g_sAccountLenErr;
extern const char *g_sPasswordNotMatch;
extern const char *g_sPasswordLenErr;
extern const char *g_sPasswordSpecial;
extern const char *g_sAccountSpecial;
extern const char *g_sCreateRole;
extern const char *g_sRoleDeletedTip;
extern const char *g_sRoleDeletedCancelTip;
extern const char *g_sGameBegin ;
extern const char *g_sFightResult ;
extern const char *g_sStageClearTime ;
extern const char *g_sHitContinuous ;
extern const char *g_sKillCount ;
extern const char *g_sStageComment ;
extern const char *g_sExpAward ;
extern const char *g_sMoneyAward ;
extern const char *g_sObjectAward ;
extern const char *g_sOK ;
extern const char *g_sYouDead ;
extern const char *g_sDiffculty[];
extern const char *g_sPhysicalCost ;
extern const char *g_sStageRefreshTimes ;
extern const char *g_sFixedAward ;
extern const char *g_sRandomAward ;
extern const char *g_sEnter ;
extern const char *g_sBaggage ;
extern const char *g_sProfessionStr[];
extern const char *g_sAddattribution[];
extern const char *g_sStageFmt ;
extern const char *g_sAttribute[];
extern const char *g_sMoneyName[];
extern const char *g_sSelectEnhanceObject ;
extern const char *g_sEnhanceFailed ;
extern const char *g_sSelectCombObject ;
extern const char *g_sCombFailed ;
extern const char *g_sQualityFmt ;
extern const char *g_sTypeFmt ;
extern const char *g_sProLimitFmt ;
extern const char *g_sIsBindFmt ;
extern const char *g_sIsUniqueFmt ;
extern const char *g_sEquipClassFmt ;
extern const char *g_sFunctionFmt ;
extern const char *g_sSalePriceFmt ;
extern const char *g_sUseTimeLimitFmt ;
extern const char *g_sProfession;
extern const char *g_sBowman ;
extern const char *g_sMagician ;
extern const char *g_sSoldier  ;
extern const char *g_sNeedLevelFmt ;
extern const char *g_sEquipScore ;
extern const char *g_sAttrib ;
extern const char *g_sExtraAttrib ;
extern const char *g_sNameLevelFmt ;
extern const char *g_sPriceFmt ;
extern const char *g_sChannel[];
extern const char *g_sInputHere ;
extern const char *g_sChat ;
extern const char *g_sSkillStr[];
extern const char *g_sSkill ;
extern const char *g_sGoldCount ;
extern const char *g_sSkillNameStr[];
extern const char *g_sAllSkillNamd[];
extern const char *g_sSkillInfo[];
extern const char *g_sAngrySkillInfoStr[];
extern const char *g_sSkillCaption ;
extern const char *g_sAngrySkill ;
extern const char *g_sAttach ;
extern const char *g_sSkillName ;
extern const char *g_sAngrySkillName ;
extern const char *g_sAttachName ;
extern const char *g_sNotOpen ;
extern const char *g_sNotStudy ;
extern const char *g_sNextClassDescription ;
extern const char *g_sNeedSkillPro;
extern const char *g_sStudy ;
extern const char *g_sUpgrade ;
extern const char *g_sMaster ;
extern const char *g_sBranch ;
extern const char *g_sSun ;
extern const char *g_sNoDialog ;
extern const char *g_sSelectTask ;
extern const char *g_sLevelLow ;
extern const char *g_sPowerNeedUpgrade ;
extern const char *g_sAccept ;
extern const char *g_sContinue ;
extern const char *g_sDone ;
extern const char *g_sSeek ;
extern const char *g_sUpgradeFmt ;
extern const char *g_sComposeTip;
extern const char *g_sLevelFmt ;
extern const char *g_sReconnectLater ;
extern const char *g_sNetworkError ;
extern const char *g_sTip ;
extern const char *g_sWaitReconnectFmt ;
extern const char *g_sWorld ;
extern const char *g_sCity ;
extern const char *g_sSystem ;
extern const char *g_sFuncNotOpen ;
extern const char *g_sUiButton[] ;
extern const char *g_Quality[];
extern const char *g_sAvoid ;
extern const char *g_sBloodBottle ;
extern const char *g_sMagicBottle ;
extern const char *g_sBagButtonStr[];
extern const char *g_sNotCouldExclude;
extern const char *g_sNotCouldAcquire;
extern const char *g_sCurrentCouldReceive;
extern const char *g_sVIPFunctionInfo;
extern const char *g_sLottery;
extern const char *g_sHeader ;
extern const char *g_sCloth ;
extern const char *g_sGlove ;
extern const char *g_sShoes ;
extern const char *g_sPet ;
extern const char *g_sWeapon ;
extern const char *g_sNecklace ;
extern const char *g_sRing;
extern const char *g_sJewelry;
extern const char *g_sWing;
extern const char *g_sRing;
extern const char *g_sJewelry;
extern const char *g_sWing;
extern const char *g_sChoiceProfession;
extern const char *g_sReliveConfirm;
extern const char *g_sYes;
extern const char *g_sNo;
extern const char *g_sConfirm;
extern const char *g_sCancel;
extern const char *g_sTreasure;
extern const char *g_sPresent;
extern const char *g_sConsumables;
extern const char *g_sMaterial;
extern const char *g_sUse;
extern const char *g_sSale;
extern const char *g_sRefreshable;
extern const char *g_sReinforce100Tip;
extern const char *g_sNotRefreshable;
extern const char *g_sLackJewel;
extern const char *g_sNeedJewelOpen;
extern const char *g_sMicrosoftAccor;
extern const char *g_sBeEquipped;
extern const char *g_sNotEquip;
extern const char *g_sIf;
extern const char *g_sReceive;
extern const char *g_sEquip;
extern const char *g_sNoEquipPos;
extern const char *g_sNoItem;
extern const char *g_sTotal;
extern const char *g_sSignUp;
extern const char *g_sNum;
extern const char *g_sCount;
extern const char *g_sReal;
extern const char *g_sGetable;
extern const char *g_sGotten;
extern const char *g_sHaveNotGet;
extern const char *g_sCanNotGet;
extern const char *g_sSymbol;
extern const char *g_sSignUpSuccess;
extern const char *g_sSignUpAddCardInsufficiency;
extern const char *g_sGet;
extern const char *g_sFindPath;
extern const char *g_sGetScore;
extern const char *g_sPointFormat;
extern const char *g_sRMBChargeJew;
extern const char *g_sLackJew;
extern const char *g_sLackGold;
extern const char *g_sLeaveDungeons;
extern const char *g_sCanNotReinforce;
extern const char *g_sCanNotType;
extern const char *g_sCanNotMiss;
extern const char *g_sCanNotLevel;
extern const char *g_sCanNotCompose;
extern const char *g_sMissingMaterialForReinforce;
extern const char *g_sMissingMaterialForCompose;
extern const char *g_sLackJewForCompose;
extern const char *g_sComposeType;
extern const char *g_sComposeMiss;
extern const char *g_sRemove;
extern const char *g_sPhagocytosis;
extern const char *g_sSure;
extern const char *g_sCanel;
extern const char *g_sCharge;
extern const char *g_sThis;
extern const char *g_sProtoss;
extern const char *g_sQuestionMark;
extern const char *g_sEquipCommAttributeProtoss;
extern const char *g_sEquipNoEmpty;
extern const char *g_sAllMerge;
extern const char *g_sChoiceChangeProtoss;
extern const char *g_sLockProtossEquip;
extern const char *g_sHaveNotEquipProtoss;
extern const char *g_sEmptyBag;
extern const char *g_sCanNotMerge;
extern const char *g_sPhysicalStrengthInsuffence;
extern const char *g_sStarPointLack;
extern const char *g_sCongratulateGetAward;
extern const char *g_sActivityOperateRequir;
extern const char* g_sLoadingMsgStr[];
extern const char* g_sUnableRegister;
extern const char *g_sPurchaseCommodity;
extern const char *g_sLightConstellation;
extern const char *g_sGrayProtossNoGet;
extern const char *g_sSwallowProtoss;
extern const char *g_sPleaseSelecteProtoss;
extern const char *g_sGetOneChoiceForAward;
extern const char *g_sBagNeedPlayerLevel;
extern const char *g_sBagNeedEquipLevel;
extern const char *g_sPaySuccess;
extern const char *g_sPayFailed;
extern const char *g_sPleaseInputCardNumber;
extern const char *g_sPleaseInputCardPassword;
extern const char *g_sPleaseSelectedChargeQuota;
extern const char *g_sChargeCardInfoTip;
extern const char *g_sDigtalTipForChargeCardInfo;
extern const char *g_sHaseePayChargeTip;
extern const char *g_ExitTip;
extern const char *g_sShopItemDesInfo;
extern const char *g_sHaseePay;
extern const char *g_sEquipPropertyLabel[];
extern const char *g_sStateUILevelTip;
extern const char *g_sNameTooLong;
extern const char *g_sNameNickName;
extern const char *g_sSelectedMail;
extern const char *g_sRoleLevelDificiency;
extern const char *g_sUpgradeSkill;
extern const char *g_sUpgradeAngry;
extern const char *g_sActivityUpdate;
extern const char *g_sBuyGold;
extern const char *g_sTrialRankName;
extern const char *g_sLackKey;
extern const char *g_sMailGMTitle;
extern const char *g_sMailGMContent;
extern const char *g_sConvertCodePlaceHolder;
extern const char *g_sAchiStatus0;
extern const char *g_sAchiStatus1;
extern const char *g_sAchiStatus2;
extern const char *g_sAchiStatusDesc0;
extern const char *g_sAchiStatusDesc1;
extern const char *g_sAchiStatusDesc2;
extern const char *g_sTurnTableGetArard;
extern const char *g_sTurnTableReceiveArard;
extern const char *g_sTurnTableLackOfTicket;
extern const char* g_sPlayTableDungeonTipMsgStr[];
extern const char* g_sPlayTableDungeonResetMsgStr;
extern const char* g_sPlayTableDungeonResetLimit;
extern const char* g_sPlayTableDungeonResetLackMsgStr;
extern const char* g_sTalentAddPoiont;
extern const char* g_sTalentReset;
extern const char* g_sPlayTableProtossTipMsgStr[];
extern const char* g_sPlayTableProtossFinish[];
extern const char* g_sPlayTableProtossBtnState[];
extern const char* g_sPlayTableProtossWipe;
extern const char* g_sPlayTableBossLackChallenge;
extern const char* g_sPlayTableBossDungeonUnabled;
extern const char* g_sPlayTableBossDungeonJew;
extern const char* g_sPlayTableBossDungeonLevel;
extern const char* g_sPlayTableBossDungeonChallenge[];
extern const char* g_sImmediatelyRelive;
extern const char* g_sWorldBossPrayConfirm;
extern const char* g_sWorldBossPraySuccess;
extern const char* g_sWorldBossKilled;
extern const char* g_sWorldBossTarget;
extern const char* g_sMobileMessagePay;